# Generated by Django 4.2.7 on 2023-11-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animal_detail',
        ),
        migrations.AddField(
            model_name='animaldetail',
            name='animal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.animal'),
        ),
    ]
