"""empty message

Revision ID: c082685f460a
Revises: 
Create Date: 2023-11-06 11:42:41.888266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c082685f460a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=255), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('stock', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('apellido', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('domicilio', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('apellido', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('domicilio', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=255), nullable=True),
    sa.Column('raza', sa.String(length=255), nullable=True),
    sa.Column('alergias', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=255), nullable=True),
    sa.Column('marca', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedores')
    op.drop_table('paciente')
    op.drop_table('doctor')
    op.drop_table('cliente')
    op.drop_table('accesorios')
    # ### end Alembic commands ###
