# Generated by Django 4.2.7 on 2023-11-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestorapp.doctor'),
        ),
    ]
